import type { Metadata } from "next";

import "@/app/_styles/globals.css";
import IRANSans from "@/app/_styles/fonts";
import Topbar from "./_components/Topbar";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR">
      <body
        className={`${IRANSans.className} font-normal antialiased min-h-screen text-bodyApp overflow-x-hidden`}
        dir="rtl"
      >
        <Topbar />
        {children}
      </body>
      <Footer />
    </html>
  );
}
